volumes:
  oracle_data:
    driver: local

services:
  oracleDatabase:
    image:  bad8logic/oracleeedbcloud:latest
    container_name: oracleDbContainer
    ports:
      - 1521:1521
    environment:
      - ORACLE_PWD=someStrongPass876
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
    volumes:
      - oracle_data:/opt/oracle/oradata